# Generated by Django 3.2.15 on 2023-10-13 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_manual_fill_prices_in_old_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'необработанный'), ('cooking', 'готовится'), ('delivery', 'доставляется'), ('closed', 'завершен')], db_index=True, default='new', max_length=15, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default=True, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена'),
        ),
    ]
