# Generated by Django 3.2.15 on 2023-10-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Необработанный'), ('cooking', 'Готовится'), ('delivery', 'Доставляется'), ('closed', 'Завершен')], db_index=True, default='new', max_length=15, verbose_name='статус'),
        ),
    ]
