# Generated by Django 3.2.15 on 2023-10-14 13:21

from django.db import migrations, models
import django.db.models.deletion
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20231013_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, limit_choices_to=foodcartapp.models.Order.get_available_restaurants, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='foodcartapp.restaurant', verbose_name='Исполнитель'),
        ),
    ]
