# Generated by Django 3.2.15 on 2023-10-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Необработанный'), (2, 'Готовится'), (3, 'Доставляется'), (4, 'Завершен')], db_index=True, default='new', max_length=15, verbose_name='статус'),
        ),
    ]
