# Generated by Django 3.2.15 on 2023-10-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(db_index=True, max_length=15, verbose_name='статус'),
        ),
    ]
