# Generated by Django 3.2.15 on 2023-10-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Необработанный'), ('COOKING', 'Готовится'), ('DELIVERY', 'Доставляется'), ('CLOSED', 'Завершен')], db_index=True, default='NEW', max_length=15, verbose_name='статус'),
        ),
    ]
